# Generated by Django 5.0 on 2024-01-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(default='Default Fullname', max_length=100, unique=True),
        ),
    ]
