# Generated by Django 5.0 on 2024-01-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0002_alter_author_fullname'),
        ('quotes_app', '0002_tag_quote_author_quote_quote_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='authors_app.author'),
        ),
    ]
