# Generated by Django 5.0 on 2024-01-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(default='', max_length=255),
        ),
    ]
