# Generated by Django 5.0 on 2023-12-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True, unique=True)),
                ('born_date', models.CharField(max_length=50)),
                ('born_location', models.CharField(max_length=150)),
                ('description', models.CharField()),
            ],
        ),
    ]
